- README.md
- lib/lago/api/connection.rb
- lib/lago/api/resources/event.rb
- spec/lago/api/resources/event_spec.rb
This adds support for `client.events.find(transaction_id)`. Not sure if `find` is the best method name - suggestions for improvement are appreciated :)
> feat: add support for finding events by transaction id

- lib/lago/api/connection.rb
- spec/lago/api/connection_spec.rb
Ensure that Lago::Api::HttpError#error_code is an integer
Fixes #17
> bug: fix HTTP response code type

- README.md
- lib/lago/api/resources/customer.rb
Add a new `sync` flag in `customer[billing_configuration]` in order to allow synchronous creation of the stripe customer. It will return the stripe customer ID immediately rather by waiting for the webhook
> feat: synchronous stripe customer creation

- README.md
- lib/lago/api/resources/customer.rb
- spec/factories/customer_usage.rb
- spec/lago/api/resources/customer_spec.rb
Add new `GET /api/v1/customers/:customer_id/current_usage` route
Related to:
- https://github.com/getlago/lago-api/pull/322
- https://github.com/getlago/lago-docs/pull/15
> feat: Add new customer current usage route

- README.md
- lib/lago/api/resources/subscription.rb
- spec/factories/subscription.rb
- spec/lago/api/resources/subscription_spec.rb
We want to add the ability to choose to bill users at subscription date anniversary and not only on a calendar basis.
The objective of this pull request is to add the support for `billing_time` attribute for subscription creation
Possible values will be `anniversary` and `calendar`
The changes are :
- Accept the new `billing_time` argument into 'POST /subscriptions'
This PR follows:
- https://github.com/getlago/lago-api/pull/352 to update the subscription data model.
- https://github.com/getlago/lago-api/pull/360 to add a new date service for invoice bounds
- https://github.com/getlago/lago-api/pull/364 to expose billing time into GraphQL
- https://github.com/getlago/lago-api/pull/365 to expose billing time into API
> feat: Allow billing_time attribute for subscription creation

- lib/lago/api/connection.rb
This change conditionally sets `use_ssl` on the http client when the URI scheme is https. Otherwise, the client will not work when developing locally and/or experimenting with the self-hosted instance.
> Only use ssl when https

- CONTRIBUTING.md
- lago-ruby-client.gemspec
Root URL of the Lago documentation has been updated from https://doc.getlago.com/docs/guide/intro to https://doc.getlago.com/docs/guide/intro/welcome in [this commit](https://github.com/getlago/lago-docs/commit/e7e99d7762b0e0d4548ccec3e78bee0d522e35da).
The goal of this PR is to update links to the Lago official documentation on this repo.
> fix: Update lago documentation url

- README.md
- lib/lago/api/resources/applied_add_on.rb
- lib/lago/api/resources/applied_coupon.rb
- lib/lago/api/resources/customer.rb
- lib/lago/api/resources/event.rb
- lib/lago/api/resources/subscription.rb
- spec/factories/applied_add_on.rb
- spec/factories/applied_coupon.rb
- spec/factories/customer.rb
- spec/factories/event.rb
- spec/factories/subscription.rb
- spec/lago/api/resources/applied_add_on_spec.rb
- spec/lago/api/resources/applied_coupon_spec.rb
- spec/lago/api/resources/customer_spec.rb
- spec/lago/api/resources/subscription_spec.rb
We want to clarify the difference between lago ids and external ids.
Today, we have `customer_id` on customers and `subscription_id|unique_id` on subscriptions.
On the API, the goal is to use external_ids:
- `external_id` or `external_customer_id` for customer
- `external_id` or `external_subscription_id` for subscription
The goal of this PR is to:
- rename `customer_id` to `external_id` on customers
- rename `subscription_id` to `external_id` on subscriptions
- remove `unique_id` from subscriptions
> misc: Use external_id instead of customer_id and subscription_id

- lib/lago/api/resources/subscription.rb
- spec/factories/subscription.rb
- spec/lago/api/resources/subscription_spec.rb
This PR adds support for `subscription_date` param when creating or updating subscription
> feat (subscriptions): add support for subscription date

- lib/lago/api/resources/billable_metric.rb
- spec/lago/api/resources/billable_metric_spec.rb
👉  https://github.com/getlago/lago/issues/32
We want to be able to price differently billable metrics according to several dimensions (groups).
For example, creating a `storage` pricing based on the `region of the server` and the `cloud provider` used.
This PR adds `group` on `billable_metric`.
> feat(groups): Add group on billable metric

- lib/lago/api/resources/customer.rb
- lib/lago/api/resources/organization.rb
- spec/factories/customer.rb
- spec/factories/organization.rb
👉  https://github.com/getlago/lago/issues/99
The goal of this PR is to move fields related to Billing or Invoice into `billing_configuration`.
For customer: `vat_rate`.
For organization: `invoice_footer`, `vat_rate`.
> misc: Move fields to billing configuration

- lib/lago/api/resources/invoice.rb
- spec/factories/invoice.rb
- spec/lago/api/resources/invoice_spec.rb
👉  https://github.com/getlago/lago/issues/99
When a billing period is over, users don’t want to invoice straight away.
They want a defined number of days to:
- Collect delayed events for usage
- Adjust invoice amounts for items
The goal of this PR is to rename `invoice#status` to `invoice#payment_status`.
`invoice#status` will be used to define if the invoice is `draft` or `finalized`.
**⚠️ This is a breaking change PR, do not merge before Dec. 8th.**
> feat(grace_period): Rename invoice#status to payment_status

- Gemfile.lock
- lib/lago/api/resources/coupon.rb
- lib/lago/api/resources/customer.rb
- lib/lago/api/resources/organization.rb
- lib/lago/api/resources/wallet.rb
- spec/factories/coupon.rb
- spec/factories/customer.rb
- spec/factories/organization.rb
- spec/factories/wallet.rb
- spec/lago/api/resources/coupon_spec.rb
- spec/lago/api/resources/customer_spec.rb
- spec/lago/api/resources/event_spec.rb
- spec/lago/api/resources/wallet_spec.rb
👉  https://github.com/getlago/lago/issues/61
It’s impossible to bill a customer following its own timezone.
Lago ingests events, creates subscription boundaries and trigger invoices on a UTC timezone, which is the same for everyone.
This feature adds the possibility to choose the timezone an organization or a customer should be billed in.
This PR adds:
- Support for timezone at customer level
- Support for timezone at organization level
- Replace `expiration_date` by `expiration_at` on coupons
- Replace `expiration_date` by `expiration_at` on wallets
> feat(timezones): Update clients to support customer timezones

- Gemfile.lock
- lib/lago/api/resources/credit_note.rb
- lib/lago/api/resources/customer.rb
- lib/lago/api/resources/invoice.rb
- lib/lago/api/resources/organization.rb
- spec/factories/customer.rb
- spec/factories/invoice.rb
- spec/factories/organization.rb
- spec/lago/api/resources/credit_note_spec.rb
- spec/lago/api/resources/customer_spec.rb
- spec/lago/api/resources/invoice_spec.rb
- spec/lago/api/resources/organization_spec.rb
The goal of this PR is to:
- add `invoice_grace_period` to organization
- add `invoice_grace_period` to customer
- add `status` to invoice
- add endpoint for refreshing an invoice
- add endpoint for finalizing an invoice
> feat: Add support for grace period

- lib/lago/api/resources/webhook.rb
- spec/lago/api/resources/webhook_spec.rb
`/api/v1/webhooks/public_key` endpoint changed reponse to json format:
{'webhook': {'public_key': 'public key encoded'}}
This PR adds support for mentioned changes
> fix (webhooks): add support for new webhook secret response payload

- Gemfile.lock
- spec/lago/api/resources/billable_metric_spec.rb
👉  https://github.com/getlago/lago/issues/179
As a user, I want to be able to delete a billable metric that is linked to a subscription in case of a change of pricing (e.g. we no longer charge customers based on the number of API calls).
Once deleted, the corresponding charges will be removed from the plans and from all draft invoices.
Deleted metrics will still be included in past invoices (i.e. finalized invoices).
The goal of this PR is to add on the billable metric response:
- `activeSubscriptionsCount`
- `draftInvoicesCount`
These fields are used to know the impact of deleting billable metric.
> feat(delete_bm): Update tests for billable metric deletion

- LICENSE copy
- README.md
- spec/lago/api/resources/plan_spec.rb
Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete plans.
The goal of this feature is to be able to soft-delete a plan linked to an active or terminated subscription.
The goal of this PR is to add two counters in the plan response:
- `active_subscription_count`
- `draft_invoice_count`
> feat(delete_plan): Add subscription and invoice counters to plans

- Gemfile.lock
- spec/lago/api/resources/customer_spec.rb
Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete customers.
The goal of this feature is to be able to soft-delete a customer linked to an active or terminated subscription.
This PR adds some specs for the new Customer destroy route added in https://github.com/getlago/lago-api/pull/779
> feat(delete_customer): Add specs for the customer destroy route

- lib/lago/api/resources/applied_coupon.rb
- spec/lago/api/resources/applied_coupon_spec.rb
**Context**
Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete customers.
The goal of this feature is to be able to soft-delete an applied coupon.
**Description**
This PR adds the destroy endpoint for applied coupon.
> feat(delete_coupon): Ability to destroy an applied coupon

- spec/lago/api/resources/billable_metric_spec.rb
- spec/lago/api/resources/plan_spec.rb
Plans edition has some issue if you update some properties of a billable metric, especially if you change groups definition or aggregation type :
"After the billable metric edition, new dimensions are created with new group_id that do not match the ones in the plans already defined"
This PR exposes a new `plans_count` field in the `BillableMetric` response type to let the API users know if the BM is editable.
Related to https://github.com/getlago/lago-api/pull/914
> feat(bm): Expose count of attached plans

- lib/lago/api/resources/fee.rb
- spec/factories/fee.rb
- spec/lago/api/resources/fee_spec.rb
👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds:
- Definition for `GET /api/v1/fees`
- Definition for `PUT /api/v1/fees/:id`
- Add new fields definition to fees:
- lago_invoice_id
- external_subscription_id
- payment_status
- created_at
- succeeded_at
- failed_at
- refunded_at
- …
> feat(instant_charge): Expose fees updapte and get all routes

- Gemfile.lock
- lib/lago/api/resources/plan.rb
- spec/factories/plan.rb
- spec/lago/api/resources/plan_spec.rb
👉  https://github.com/getlago/lago/issues/149
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR allows having an instant charge.
> feat(instant_charge): Ability to have an instant charge

- spec/factories/invoice.rb
Update `Invoice` definition:
- `currency`
- `fees_amount_cents`
- `coupons_amount_cents`
- `credit_notes_amount_cents`
- `sub_total_vat_excluded_amount_cents`
- `sub_total_vat_included_amount_cents`
- `prepaid_credit_amount_cents`
- `legacy`
- `amount_currency`
- `vat_amount_currency`
- `credit_amount_currency`
- `total_amount_currency`
- `amount_cents`
- `credit_amount_cents`
> feat(invoice): Refactoring on invoice amounts

- lib/lago/api/resources/wallet.rb
This PR allows the `currency` param to be sent for the `Wallet` resource. Otherwise, creating a wallet when the customer has a non-USD currency errors with `currencies_does_not_match`.
> Allow currency param for wallet

- lib/lago/api/resources/credit_note.rb
- lib/lago/api/resources/invoice.rb
- spec/lago/api/resources/invoice_spec.rb
When `download` action is triggered for `invoice` or `credit_note` collection, there are 2 scenarios:
1. File has already been generated and invoice object is returned
2. File has not been generated yet; Job is scheduled and empty response is returned
> fix: update support for download invoice and credit note

- lib/lago/api/resources/credit_note.rb
- spec/lago/api/resources/credit_note_spec.rb
Credit note item whitelisting is not aligned with the documentation and expectation on Lago API.
API is expecting for an `amount_cents` attribute, while this SDK is whitelisting `credit_amount_cents` and `refund_amount_cents`.
This PR fixes the implementation by replacing the item attribute whitelisting with `amount_cents`
> fix(credit-note): Item amount whitlisting

- Gemfile.lock
- lib/lago/api/resources/credit_note.rb
- lib/lago/version.rb
Credit note whitelisting is not aligned with the documentation and expectation on Lago API.
API is expecting for a `credit_amount_cents` or `refund_amount_cents` attribute, while this SDK is whitelisting not whitelisting them
This PR fixes the implementation by adding `credit_amount_cents` and `refund_amount_cents` to the attribute whitelisting
> fix(credit-note): Accept credit_amount_cents and refund_amount_cents

- lib/lago/api/resources/coupon.rb
- spec/factories/coupon.rb
- spec/lago/api/resources/coupon_spec.rb
This PR adds the coupon's description attribute now available
> feat: add description field to coupons

- lib/lago/api/connection.rb
- lib/lago/api/resources/base.rb
- spec/lago/api/resources/subscription_spec.rb
This PR adds 2 improvements
1. you can now delete a pending subscription by passing a `status=pending` as query param
2. You can now filter `GET /subscriptions` by passing an array of status as query param
> feat(subscription) allow to pass status to index and delete

- lib/lago/api/resources/add_on.rb
- lib/lago/api/resources/invoice.rb
- spec/factories/add_on.rb
- spec/factories/tax.rb
- spec/fixtures/api/customer.json
- spec/fixtures/api/invoice.json
- spec/fixtures/api/organization.json
- spec/fixtures/api/tax.json
- spec/fixtures/api/taxes.json
- spec/lago/api/resources/add_on_spec.rb
- spec/lago/api/resources/invoice_spec.rb
👉  [https://getlago.canny.io/feature-requests/p/create-several-tax-rates](https://getlago.canny.io/feature-requests/p/create-several-tax-rates)
After the delivery of the "multiple taxes" feature https://github.com/getlago/lago-api/pull/1104, we now want to be able to define taxes at add ons level.
This PR adds the ability to assign taxes on add on create/update.
> feat(tax): Add taxes to add ons

- lib/lago/api/resources/plan.rb
Fix for `undefined method 'each' for nil:NilClass (NoMethodError)` when calling `client.plans.update(plan, "__identifier__")` on a plan with empty `charges`
> Fix: Add a safe navigator in the `whitelist_charges` method for `Plan`

- lib/lago/api/resources/coupon.rb
- spec/fixtures/api/coupon.json
- spec/lago/api/resources/coupon_spec.rb
Call to `GET /v1/api/coupons/:code` is missing the `terminated_at` value
This PR is adding the missing field in the `V1::CouponSerializer`
> fix(coupon): Add missing coupons#terminated_at

- lib/lago/api/resources/billable_metric.rb
- spec/factories/billable_metric.rb
- spec/fixtures/api/billable_metric.json
- spec/fixtures/api/billable_metric_index.json
- spec/lago/api/resources/billable_metric_spec.rb
- spec/lago/api/resources/group_spec.rb
For metrics that are charged upon a time frame, Lago is not able to calculate correctly the charge. For instance, imagine you want to price the number of GB/seconds used by a server. Currently, you can either calculate the number of seconds used, or the number of Gigabytes used, but not both at the same time.
This PR adds:
- the new `Event#timestamp` format with miliseconds precision
- The new `weighted_sum_agg` aggregation value in the `BillableMetric#aggregation_type` enumeation
- The new `BillableMetric#weighted_interval` enum
> feat(weighted-sum): Add weighted sum fields to billable metric

- spec/lago/api/resources/subscription_spec.rb
We want to improve the way we are overriding a plan. Without working as a duplicate, by adding the logic for managing parent and children of plans.
The goal of this PR is to add the endpoint `GET /api/v1/subscriptions/:external_id`.
> feat(override-plan): Ability to fetch a single subscription

- lib/lago/api/resources/add_on.rb
- lib/lago/api/resources/invoice.rb
- lib/lago/api/resources/plan.rb
- spec/factories/add_on.rb
- spec/factories/plan.rb
- spec/fixtures/api/credit_note.json
- spec/fixtures/api/fee.json
- spec/fixtures/api/invoice.json
- spec/lago/api/resources/add_on_spec.rb
- spec/lago/api/resources/fee_spec.rb
- spec/lago/api/resources/plan_spec.rb
Add a custom name to display on invoice for subscription fee and charges
When generating an invoice, don't display the name of the plan or the name of the billable metrics to the customer.
> feat(invoice_display_name): Add invoice display name

- lib/lago/api/resources/customer.rb
- spec/fixtures/api/customer_past_usage.json
- spec/fixtures/api/customer_usage.json
- spec/lago/api/resources/customer_spec.rb
Some of our users want to retrieve usage in the past. The main problem they are facing is that at the beginning of a new period, they cannot compute usage in third party systems, or see if everything went well as usage for the past period has been removed.
This PR adds a new route to fetch the past_usage for a customer/subscription.
> feat(past_usage): Expose route to fetch customer past usage

- Gemfile.lock
- lib/lago/api/connection.rb
- spec/lago/api/connection_spec.rb
This PR fixes a [bug](https://github.com/getlago/lago-ruby-client/issues/136#event-11026146821).
Identifier in the url is not encoded properly.
> fix(encoding): Fix identifier encoding

- lib/lago/api/resources/organization.rb
- spec/factories/organization.rb
- spec/fixtures/api/organization.json
- spec/lago/api/resources/organization_spec.rb
Before, it was not possible to adapt document number. With this feature it will be enabled to switch between `per_customer` and `per_organization` document numbering logic. Also, it will be possible to edit number prefix.
This PR adds support for new document numbering fields
> feat (document-numbering): Add support for new document numbering fields

- lib/lago/api/resources/customer.rb
- spec/lago/api/resources/customer_spec.rb
- Fix `URI::InvalidURIError` in `client.customers.checkout_url`
- Add tests to the function
- Fixes https://github.com/getlago/lago-ruby-client/issues/167
The checkout_url function should successfully call the POST API and return the following object:
```
{
"checkout_url": "https://foo.bar",
"external_customer_id": "5eb02857-a71e-4ea2-bcf9-57d3a41bc6ba",
"lago_customer_id": "1a901a90-1a90-1a90-1a90-1a901a901a90",
"payment_provider": "stripe"
}
```
> Fix URI::InvalidURIError in client.customers.checkout_url

- lib/lago/api/resources/invoice.rb
- spec/lago/api/resources/invoice_spec.rb
This PR adds support for invoice payment url
> feat (invoice-payment-url): add support for invoice payment url

- Gemfile.lock
- lib/lago/api/resources/plan.rb
- spec/factories/minimum_commitment.rb
- spec/factories/plan.rb
- spec/fixtures/api/plan.json
- spec/fixtures/api/plans.json
- spec/lago/api/resources/plan_spec.rb
- spec/lago/api/resources/subscription_spec.rb
👉  https://getlago.canny.io/feature-requests/p/set-minimum-spend-for-subscriptions
As a user, I want to define the minimum spend that applies to the customer's plan. Consider the following monthly plan:
- Subscription fee = $50 per month (in arrears);
- Usage-based charge = $10 per unit per month (in arrears); and
- Monthly minimum spend = $100.
If at the end of the month, the customer has consumed 3 units, their total invoice will be: $50 + 3 * $10 = $80 + $20 (true-up fee) = $100.
This PR adds minimum commitment to plan and plan overrides.
> feat(minimum-commitment): Add minimum commitment

- spec/lago/api/resources/wallet_spec.rb
The goal of this PR is to add `recurring_transaction_rules` to `WalletsController#index`.
> feat: Add recurring_transaction_rules to WalletsController#index

- lib/lago/api/resources/billable_metric.rb
- lib/lago/api/resources/plan.rb
- spec/fixtures/api/billable_metric.json
- spec/fixtures/api/billable_metric_index.json
- spec/fixtures/api/customer_past_usage.json
- spec/fixtures/api/customer_usage.json
- spec/fixtures/api/fee.json
- spec/fixtures/api/plan.json
- spec/fixtures/api/plans.json
Lago is not currently supporting more than 2 levels of event grouping (parent → children)
The goal of this feature is to allow more flexibility of event grouping by allowing an unlimited level of grouping and making it easier to define default charge properties for events based on their properties.
This PR is related to https://github.com/getlago/lago-openapi/pull/210
It adds the new filter fields in both input and output objects
> feat(filter): Add filter fields

- Gemfile.lock
- lib/lago/api/resources/wallet_transaction.rb
- spec/factories/wallet_transaction.rb
We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to create a voided wallet transaction.
> feat(wallet): Add voided_credits to WalletTransaction

- lib/lago/api/resources/wallet.rb
- spec/factories/wallet.rb
- spec/lago/api/resources/wallet_spec.rb
After the release of real-time wallet version 1, some customers have expressed concerns about odd or missing behaviors.
The goal of this PR is to rename `Wallet#rule_type` into `Wallet#trigger`.
> feat(wallet): Rename wallet rule_type into trigger

- lib/lago/api/resources/wallet.rb
- spec/factories/wallet.rb
👉 https://getlago.canny.io/feature-requests/p/define-a-target-balance-to-reach-for-recurring-top-up
We want to allow users to top-up their wallets to reach a specific target balance.
We can currently define a fixed top-up but we want to add the ability to specify a dynamic top-up (target balance to reach).
The goal of this PR is to add:
- `method`
- `target_ongoing_balance`
- `started_at`
to `recurring_transaction_rule`
> feat(wallet): Add method and target_ongoing_balance to recurring_transaction_rule

- spec/fixtures/api/invoice.json
- spec/lago/api/resources/invoice_spec.rb
👉 https://getlago.canny.io/feature-requests/p/regroup-invoices-to-generate-one-payment-intent
We want to be able to group invoices to generate one payment.
Today we don't track payment terms and do not mention whether a payment or an invoice is overdue.
The goal of this PR is to add:
- `payment_overdue_since`
to `invoice`
> feat(dunning): Add payment_overdue_since to invoice

- lib/lago/api/resources/customer.rb
- spec/factories/customer.rb
- spec/fixtures/api/customer.json
- spec/lago/api/resources/customer_spec.rb
This PR adds support for shipping address that will be used in tax integrations.
> feat(customers): add support for shippig address

- Gemfile.lock
- lib/lago/version.rb
As announced a few months ago, this release updates the event ingestion process and removes deprecated API fields.
Changes include:
The new dimension system based on filters is already available. It allows users to create billable metrics with more than two dimensions, and makes it easier to create charges based on custom event properties. The former dimension system based on groups is now permanently removed from the Lago API ([see all changes](https://docs.getlago.com/guide/migration/migration-to-v1.2.0#1-transition-from-group-to-filters)).
Events that only include external_customer_id will no longer be taken into account when aggregating usage ([learn more](https://docs.getlago.com/guide/migration/migration-to-v1.2.0#2-mandatory-external-subscription-id-field-in-event-payloads)). This …
> misc(version): Bump to v1.7.0

- lib/lago/api/client.rb
- lib/lago/api/resources/event.rb
- spec/lago/api/client_spec.rb
- spec/lago/api/resources/event_spec.rb
This PR adds the support for the future ingest API for events on Lago US cluster.
Support for EU cluster and self-hosted will come later
> feat(event): Add support for ingest API

- lib/lago/api/resources/subscription.rb
- spec/factories/lifetime_usage.rb
- spec/fixtures/api/subscription_lifetime_usage.json
- spec/lago/api/resources/subscription_spec.rb
AI companies want their users to pay before the end of a period if usage skyrockets. The problem being that self-serve companies can overuse their API without paying, triggering lots of costs on their side.
This PR adds new routes to fetch and update the lifetime usage of a subscription
> feat(ProgressiveBilling): Expose lifetime usage GET and PUT

- lib/lago/api/resources/event.rb
- spec/factories/event.rb
- spec/fixtures/api/event.json
AI, CPaaS and Fintech customers can apply a price to a unit that fluctuates over time. Currently Lago does not support this usecase.
This PR is related to https://github.com/getlago/lago-api/pull/2610.
It documents the new `precise_total_amount_cents` in input and result payloads on `POST /api/v1/events` and `POST /api/v1/batch_events`
> feat(DynamicPricing): Expose Event#precise_total_amount_cents

- spec/fixtures/api/fee.json
- spec/fixtures/api/invoice.json
Related to https://github.com/getlago/lago-api/pull/2710
Exposes the new `fees#charge_id` field
> feat(fee): Expose charge_id

- spec/fixtures/api/billable_metric.json
- spec/fixtures/api/billable_metric_index.json
- spec/fixtures/api/plan.json
- spec/fixtures/api/plans.json
- spec/fixtures/api/tax.json
- spec/fixtures/api/taxes.json
The API response are returning a lot of counters. Since the exposed resources can be linked to a lot of objects and can be called a lot, these counters are posing a scalability problem and are slowing down the global performance of the API.
To remediate the situation the decision was made to remove all these fields.
This PR removes the following fields:
- BillableMetric
-  active_subscriptions_count
- draft_invoices_count
- plans_count
- Plan
- active_subscriptions_count
- draft_invoices_count
- Tax
- add_ons_count
- charges_count
- customers_count
- plans_count
> misc: Remove *_count fields

- .github/workflows/ci.yml
- .github/workflows/gem-push.yml
- Gemfile.lock
- lago-ruby-client.gemspec
This PR:
- Removes support for ruby 2.7 as it is unsupported for a long time now 
- Adds support for ruby 3.4
> misc: Update supported ruby versions

- lib/lago/api/resources/customer.rb
- spec/lago/api/resources/customer_spec.rb
Updated the current_usage method to accept an optional apply_taxes parameter, defaulting to True. This parameter is included in the query string as a lowercase string ("true" or "false").
> feat: add apply taxes params to current usage

- lib/lago/api/resources/wallet.rb
- spec/factories/wallet.rb
- spec/lago/api/resources/wallet_spec.rb
This PR adds support for limiting wallet consumption on specific billable metric types.
New attribute called `billable_metric_codes` is added inside `applies_to` object in both request and response.
> feat(wallets): add support for wallet bm limitation

- lib/lago/api/resources/wallet_transaction.rb
- spec/factories/wallet_transaction.rb
- spec/lago/api/resources/wallet_transaction_spec.rb
👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4256.
This implements the new input/field on wallet transactions and add tests for those.
> feat(wallet-transaction): Add a `name` to wallet transactions

- lib/lago/api/client.rb
- lib/lago/api/resources/customers/applied_coupon.rb
- lib/lago/api/resources/customers/base.rb
- lib/lago/api/resources/customers/credit_note.rb
- lib/lago/api/resources/customers/invoice.rb
- lib/lago/api/resources/customers/payment.rb
- lib/lago/api/resources/customers/payment_request.rb
- lib/lago/api/resources/customers/subscription.rb
- lib/lago/api/resources/customers/wallet.rb
- spec/fixtures/api/applied_coupon.json
- spec/fixtures/api/subscription.json
- spec/fixtures/api/wallet.json
- spec/lago/api/resources/customers/applied_coupon_spec.rb
- spec/lago/api/resources/customers/credit_note_spec.rb
- spec/lago/api/resources/customers/invoice_spec.rb
- spec/lago/api/resources/customers/payment_request_spec.rb
- spec/lago/api/resources/customers/payment_spec.rb
- spec/lago/api/resources/customers/subscription_spec.rb
- spec/lago/api/resources/customers/wallet_spec.rb
This PR follows a critical issue on the `GET /api/v1/invoices` when requests were filtered by `external_customer_id` from the GO SDK client. See https://github.com/getlago/lago-go-client/pull/288
A new set of endpoints have been added to retrieve resources scoped to a specific customer.
This PR adds the clients for all the newly created routes:
- `/api/v1/customers/:customer_external_id/applied_coupons`
- `/api/v1/customers/:customer_external_id/credit_notes`
- `/api/v1/customers/:customer_external_id/invoices`
- `/api/v1/customers/:customer_external_id/payment_requests`
- `/api/v1/customers/:customer_external_id/payments`
- `/api/v1/customers/:customer_external_id/subscriptions`
- `/api/v1/customers/:customer_external_id/wallets`
Related to:
- …
> feat(customers): Add new routes scoped to cusomters

- lib/lago/api/resources/wallet.rb
- spec/factories/wallet.rb
- spec/lago/api/resources/wallet_spec.rb
👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4282.
This adds a `transaction_name` to the wallet transaction recurring rule types that are then used to populate the name of the triggered wallet transactions.
> feat(wallet-transaction): Add `transaction_name` to wallet transaction rules

- lib/lago/api/resources/wallet.rb
- spec/lago/api/resources/wallet_spec.rb
👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4327.
This allows to provide a `name` for the wallet transactions created when creating a wallet via the `transaction_name` field.
> feat(wallet): Allow to set the name of a wallet's initial transactions
