getlago/lago-ruby-client

README.md
lib/lago/api/resources/base.rb
lib/lago/api/resources/customer.rb
spec/factories/customer.rb
spec/lago/api/resources/customer_spec.rb

Fixes https://github.com/getlago/lago-ruby-client/issues/19

[FEAT]: Add support for billing configuration for stripe

---

lib/lago/version.rb

misc: Version 0.2.0

---

README.md
lib/lago/api/resources/plan.rb
spec/factories/plan.rb
spec/lago/api/resources/plan_spec.rb

- Remove Plan Charges `amount_currency` that will be removed on the API

feat: Remove Plan Charge Currency

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md

Update the contribution guide to improve the contribution experience:
- Fix links to community slack
- Fix link to feature request tool
- Fix issues and pull request labels

misc: Update and fix contribution guide

---

.github/workflows/ci.yml
.gitignore
Gemfile.lock
spec/lago/api/resources/wallet_spec.rb

Expose wallet balance in cents for align with last updates on API

feat: Output wallet balance in cents

---

lib/lago/api/resources/subscription.rb

As per documentation: https://doc.getlago.com/docs/api/subscriptions/create-subscription

Add `subscription_at` to Subscription resource

---

Gemfile.lock
lib/lago/api/resources/customer.rb
lib/lago/api/resources/organization.rb
spec/factories/customer.rb
spec/factories/organization.rb
spec/lago/api/resources/customer_spec.rb
spec/lago/api/resources/organization_spec.rb

Expose new tax_identification_number attribute on customer and organization model

feat: add tax_identification_number to customer and organization

---

lib/lago/api/resources/event.rb
spec/fixtures/api/event.json
spec/lago/api/resources/event_spec.rb

On the path for high volume improvements, we need to adapt the structure of the events table for better performance.
This PR updates the Event.Create route to return the created event

feat(event): Update event client

---

lib/lago/api/resources/credit_note.rb
spec/factories/credit_note.rb
spec/fixtures/api/credit_note.json
spec/fixtures/api/credit_note_estimated.json
spec/lago/api/resources/credit_note_spec.rb

Add route for https://github.com/getlago/lago-api/pull/1412

feat(credit-note): Add estimate route before creation

---

lib/lago/api/resources/customer.rb

- Add the `checkout_url` endpoint for `customers`  resource

feat(customers): Add checkout_url endpoint

---

lib/lago/api/resources/customer.rb
spec/factories/customer.rb
spec/fixtures/api/customer.json
spec/fixtures/api/invoice.json

Add payment_provider_code to customer's billing configuration.

feat(psp-accounts): Add payment_provider_code

---

lib/lago/api/resources/customer.rb
spec/factories/customer.rb
spec/fixtures/api/customer.json
spec/lago/api/resources/customer_spec.rb

Change `integration_customer` param to `integration_customers`

misc: Change integration_customer param to integration_customers

---

lib/lago/api/resources/customer.rb
spec/fixtures/api/customer.json
spec/lago/api/resources/customer_spec.rb

This PR updates integration customer definition

feat(integration-customers): update integration customer definition

---

lib/lago/api/resources/plan.rb

See https://github.com/getlago/lago-api/pull/2232

feat(charges): Add Charge.regroup_paid_fees attribute

---

lib/lago/api/resources/wallet.rb
lib/lago/api/resources/wallet_transaction.rb

add wallet transaction metadata added on this pr https://github.com/getlago/lago-api/pull/2406

feat(wallet): add metadata to wallet transaction

---

lib/lago/api/resources/plan.rb

Add support for `usage_threshold` fields in the Plan Resource

feat(ProgressiveBilling) Add usage_thresholds to Resources::Plan

---

lib/lago/api/resources/customer.rb
lib/lago/api/resources/organization.rb
spec/factories/customer.rb
spec/fixtures/api/customer.json
spec/fixtures/api/organization.json
spec/lago/api/resources/customer_spec.rb

Add `finalize_zero_amount_invoice` to the organization and customer this was added on this pr  https://github.com/getlago/lago-api/pull/2462

Feat(invoice): Feat add skip zero invoices

---

spec/fixtures/api/invoice.json

The goal of this PR is to add current billing period dates at the subscription level.

feat: Add current billing period dates

---

.github/workflows/gem-push.yml

Align gem push action with ci action and use v1 version of ruby-setup.

Fix gem push action

---

lib/lago/api/resources/plan.rb

Add cascade_updates parameter to plan parameters

Feat: add cascade plan to plan params

---

lib/lago/api/resources/wallet.rb
spec/factories/wallet.rb
spec/lago/api/resources/wallet_spec.rb

Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. You have a descriptive commit message with a short title (first line).
c. You have only one commit (if not, squash them into one commit).
d. `bundle exec rspec` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to your PR.
b. Describe your changes.
c. Put `closes #XXXX` in your comment to auto-close the …

feat: add recurring transaction rules expiration

---

.gitignore
lib/lago/api/resources/invoice.rb
spec/lago/api/resources/invoice_spec.rb

Fixes https://github.com/getlago/lago-ruby-client/issues/247
Thist PR add the missing Invoice#void action

feat(invoice): Add missing void action

---

lib/lago/api/resources/wallet.rb
spec/factories/wallet.rb
spec/lago/api/resources/wallet_spec.rb

This PR adds support for wallet limitation attributes

feat(wallet-limitations): add support for wallet fee limitation

---

lib/lago/api/resources/invoice.rb
spec/fixtures/api/voided_invoice.json
spec/lago/api/resources/invoice_spec.rb

Added void invoice with the new params

feat: Added void invoice endpoint

---

Gemfile.lock
lib/lago/version.rb

Related to https://github.com/getlago/lago/releases/tag/v1.31.0

misc(version): Bump version to 1.31.0

---

lib/lago/api/resources/payment_request.rb

This PR adds the parameter payment_status to PaymentRequests.

add payment_status filter to payment requests

---

Gemfile.lock
lib/lago/version.rb

Chore: v1.33.1
